-- 코드를 입력하세요
# SELECT FIRST_HALF.FLAVOR
# FROM FIRST_HALF
# LEFT JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
# WHERE (TOTAL_ORDER > 3000) AND (INGREDIENT_TYPE = "fruit_based")
# ORDER BY TOTAL_ORDER

SELECT f.FLAVOR
FROM FIRST_HALF f JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
WHERE TOTAL_ORDER > 3000 
AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC