-- 코드를 입력하세요
SELECT concat('/home/grep/src/',concat(b.BOARD_ID,concat('/', concat( FILE_ID ,concat(FILE_NAME, FILE_EXT))))) as FILE_PATH
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC